bf16: true
cutoff_len: 4096
dataset: dpo_train_val
dataset_dir: data
ddp_timeout: 180000000
do_train: true
double_quantization: true
enable_thinking: false
eval_steps: 100
eval_strategy: steps
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 16
include_num_input_tokens_seen: true
learning_rate: 5.0e-07
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: /root/autodl-tmp/Qwen2.5-7B-Instruct
num_train_epochs: 1.0
optim: adamw_torch
output_dir: /root/autodl-tmp/LLaMA-Factory/saves/qwen2.5-7b/qlora_dpo_v2
packing: false
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
plot_loss: true
pref_beta: 0.1
pref_ftx: 0
pref_loss: sigmoid
preprocessing_num_workers: 16
quantization_bit: 4
quantization_method: bnb
report_to: none
save_steps: 100
stage: dpo
template: qwen
trust_remote_code: true
val_size: 0.111
warmup_steps: 0
