adapter_name_or_path: /root/autodl-tmp/LLaMA-Factory/saves/qwen2.5-7b/qlora_news_v4
cutoff_len: 4096
dataset_dir: data
ddp_timeout: 180000000
do_predict: true
double_quantization: true
eval_dataset: news_test
finetuning_type: lora
flash_attn: auto
max_new_tokens: 100
max_samples: 100000
model_name_or_path: /root/autodl-tmp/Qwen2.5-7B-Instruct
output_dir: /root/autodl-tmp/LLaMA-Factory/outputs/v4.1
per_device_eval_batch_size: 2
predict_with_generate: true
preprocessing_num_workers: 16
quantization_bit: 4
quantization_method: bnb
report_to: none
stage: sft
temperature: 0.1
template: qwen
top_p: 0.7
trust_remote_code: true
